using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Management;
using System.Net;
using System.Net.NetworkInformation;
using System.Security.Principal;
using LibreHardwareMonitor.Hardware;
using Spectre.Console;
namespace Task_Manager_T4;

public class UpdateVisitor : IVisitor
{
    public void VisitComputer(IComputer computer)
    {
        computer.Traverse(this);
    }
    public void VisitHardware(IHardware hardware)
    {
        hardware.Update();
        foreach (IHardware subHardware in hardware.SubHardware) subHardware.Accept(this);
    }
    public void VisitSensor(ISensor sensor) { }
    public void VisitParameter(IParameter parameter) { }
}

class InfoPC
{
    private static void Header(StreamWriter sw)
    {
        sw.WriteLine("=== SYSTEM REPORT ===");
        sw.WriteLine($"Date: {DateTime.Now}");
        sw.WriteLine($"Generated by: Task Manager T4");
    }
    private static void GeneralInfo(StreamWriter sw)
    {
        sw.WriteLine("=== GENERAL INFO ===");
        sw.WriteLine($"Computer: {Environment.MachineName}");
        sw.WriteLine($"User: {Environment.UserName}");
        sw.WriteLine($"Domain: {Environment.UserDomainName}");
        sw.WriteLine($"OS: {Environment.OSVersion}");
        sw.WriteLine($"64-bit OS: {Environment.Is64BitOperatingSystem}");
        sw.WriteLine($".NET Version: {Environment.Version}");
        sw.WriteLine($"Processors: {Environment.ProcessorCount}");
        sw.WriteLine($"Admin: {IsUserAdministrator()}");
        sw.WriteLine($"System Directory: {Environment.SystemDirectory}");
        sw.WriteLine($"Current Directory: {Environment.CurrentDirectory}");
        sw.WriteLine($"Uptime: {TimeSpan.FromMilliseconds(Environment.TickCount):dd\\.hh\\:mm\\:ss}");
    }
    private static void HardwareInfo(StreamWriter sw)
    {
        sw.WriteLine("=== HARDWARE INFO ===");
        try
        {
            sw.WriteLine("[CPU]");
            using (var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_Processor"))
            {
                foreach (ManagementObject obj in searcher.Get().Cast<ManagementObject>())
                {
                    sw.WriteLine($"  Name: {obj["Name"]}");
                    sw.WriteLine($"  Manufacturer: {obj["Manufacturer"]}");
                    sw.WriteLine($"  Cores: {obj["NumberOfCores"]}");
                    sw.WriteLine($"  Threads: {obj["NumberOfLogicalProcessors"]}");
                    sw.WriteLine($"  Current Clock: {obj["CurrentClockSpeed"]} MHz");
                    sw.WriteLine($"  Max Clock: {obj["MaxClockSpeed"]} MHz");
                    sw.WriteLine($"  L2 Cache: {obj["L2CacheSize"]} KB");
                    sw.WriteLine($"  L3 Cache: {obj["L3CacheSize"]} KB");
                    sw.WriteLine($"  Architecture: {GetArchitecture(Convert.ToInt32(obj["Architecture"]))}");
                    sw.WriteLine($"  Socket: {obj["SocketDesignation"]}");
                }
            }
            sw.WriteLine();
            sw.WriteLine("[GPU]");
            using (var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_VideoController"))
            {
                foreach (ManagementObject obj in searcher.Get().Cast<ManagementObject>())
                {
                    sw.WriteLine($"  Name: {obj["Name"]}");
                    sw.WriteLine($"  Adapter RAM: {Convert.ToUInt64(obj["AdapterRAM"]) / (1024 * 1024)} MB");
                    sw.WriteLine($"  Driver Version: {obj["DriverVersion"]}");
                    sw.WriteLine($"  Driver Date: {obj["DriverDate"]}");
                    sw.WriteLine($"  Resolution: {obj["CurrentHorizontalResolution"]}x{obj["CurrentVerticalResolution"]}");
                    sw.WriteLine($"  Color Depth: {obj["CurrentBitsPerPixel"]} bits");
                    sw.WriteLine($"  Refresh Rate: {obj["CurrentRefreshRate"]} Hz");
                }
            }
            sw.WriteLine();
            sw.WriteLine("[RAM]");
            using (var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_PhysicalMemory"))
            {
                ulong totalRam = 0;
                int ramSlots = 0;

                foreach (ManagementObject obj in searcher.Get().Cast<ManagementObject>())
                {
                    ramSlots++;
                    ulong capacity = Convert.ToUInt64(obj["Capacity"]);
                    totalRam += capacity;

                    sw.WriteLine($"  Slot {ramSlots}:");
                    sw.WriteLine($"    Capacity: {capacity / (1024 * 1024 * 1024)} GB");
                    sw.WriteLine($"    Speed: {obj["Speed"]} MHz");
                    sw.WriteLine($"    Manufacturer: {obj["Manufacturer"]}");
                    sw.WriteLine($"    Part Number: {obj["PartNumber"]}");
                    sw.WriteLine($"    Serial: {obj["SerialNumber"]}");
                    sw.WriteLine($"    Type: {GetMemoryType(Convert.ToInt32(obj["MemoryType"]))}");
                }

                sw.WriteLine($"  Total RAM: {totalRam / (1024 * 1024 * 1024)} GB ({ramSlots} slots)");
            }
            sw.WriteLine();
            sw.WriteLine("[MOTHERBOARD]");
            using (var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_BaseBoard"))
            {
                foreach (ManagementObject obj in searcher.Get().Cast<ManagementObject>())
                {
                    sw.WriteLine($"  Manufacturer: {obj["Manufacturer"]}");
                    sw.WriteLine($"  Model: {obj["Product"]}");
                    sw.WriteLine($"  Version: {obj["Version"]}");
                    sw.WriteLine($"  Serial: {obj["SerialNumber"]}");
                }
            }
            sw.WriteLine();
            sw.WriteLine("[BIOS]");
            using (var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_BIOS"))
            {
                foreach (ManagementObject obj in searcher.Get().Cast<ManagementObject>())
                {
                    sw.WriteLine($"  Manufacturer: {obj["Manufacturer"]}");
                    sw.WriteLine($"  Version: {obj["Version"]}");
                    sw.WriteLine($"  Serial: {obj["SerialNumber"]}");
                    sw.WriteLine($"  Release Date: {obj["ReleaseDate"]}");
                }
            }
        }
        catch { }
    }
    private static void NetWorkAdapters(StreamWriter sw)
    {
        sw.WriteLine("[NETWORK ADAPTERS]");
        var networkInterfaces = NetworkInterface.GetAllNetworkInterfaces();
        foreach (var ni in networkInterfaces)
        {
            if (ni.OperationalStatus == OperationalStatus.Up)
            {
                sw.WriteLine($"  Adapter: {ni.Name}");
                sw.WriteLine($"    Type: {ni.NetworkInterfaceType}");
                sw.WriteLine($"    Description: {ni.Description}");
                sw.WriteLine($"    MAC: {ni.GetPhysicalAddress()}");
                sw.WriteLine($"    Speed: {ni.Speed / 1000000} Mbps");
                sw.WriteLine($"    Status: {ni.OperationalStatus}");
                var stats = ni.GetIPv4Statistics();
                sw.WriteLine($"    Bytes Received: {stats.BytesReceived / (1024 * 1024)} MB");
                sw.WriteLine($"    Bytes Sent: {stats.BytesSent / (1024 * 1024)} MB");
            }
        }
    }
    private static void StorageInfo(StreamWriter sw)
    {
        sw.WriteLine("=== STORAGE INFO ===");
        try
        {
            var physicalDisks = new Dictionary<string, (string Model, string Serial)>();

            try
            {
                using var searcher = new ManagementObjectSearcher("SELECT * FROM Win32_DiskDrive");
                foreach (ManagementObject disk in searcher.Get().Cast<ManagementObject>())
                {
                    string deviceId = disk["DeviceID"]?.ToString() ?? "";
                    string model = disk["Model"]?.ToString()?.Trim() ?? "Unknown Model";
                    string serial = disk["SerialNumber"]?.ToString()?.Trim() ?? "Unknown Serial";

                    physicalDisks[deviceId] = (model, serial);

                }
            }
            catch (Exception e)
            {
                sw.WriteLine($"  WMI Disk Info Error: {e.Message}");
            }

            foreach (var drive in DriveInfo.GetDrives().Where(d => d.IsReady))
            {
                try
                {
                    double totalGB = drive.TotalSize / (1024.0 * 1024.0 * 1024.0);
                    double freeGB = drive.TotalFreeSpace / (1024.0 * 1024.0 * 1024.0);
                    double usedGB = totalGB - freeGB;
                    double usedPercent = totalGB > 0 ? usedGB / totalGB * 100 : 0;

                    sw.WriteLine($"[{drive.Name.TrimEnd('\\')}]");

                    (string Model, string Serial) diskInfo = ("Unknown Model", "Unknown Serial");

                    using (var partitionSearcher = new ManagementObjectSearcher(
                        $"ASSOCIATORS OF {{Win32_LogicalDisk.DeviceID='{drive.Name.Replace("\\", "")}'}} WHERE ResultClass=Win32_DiskPartition"))
                    {
                        foreach (ManagementObject partition in partitionSearcher.Get().Cast<ManagementObject>())
                        {
                            using var diskSearcher = new ManagementObjectSearcher(
                                $"ASSOCIATORS OF {{Win32_DiskPartition.DeviceID='{partition["DeviceID"]}'}} WHERE ResultClass=Win32_DiskDrive");
                            foreach (ManagementObject disk in diskSearcher.Get().Cast<ManagementObject>())
                            {
                                string deviceId = disk["DeviceID"]?.ToString() ?? "";
                                if (physicalDisks.TryGetValue(deviceId, out var info))
                                {
                                    diskInfo = info;
                                }

                            }
                        }
                    }
                    sw.WriteLine($"  Model: {diskInfo.Model}");
                    sw.WriteLine($"  Serial: {diskInfo.Serial}");
                    sw.WriteLine($"  Label: {drive.VolumeLabel}");
                    sw.WriteLine($"  Type: {drive.DriveType}");
                    sw.WriteLine($"  Format: {drive.DriveFormat}");
                    sw.WriteLine($"  Total: {totalGB:F2} GB");
                    sw.WriteLine($"  Free: {freeGB:F2} GB");
                    sw.WriteLine($"  Used: {usedGB:F2} GB ({usedPercent:F1}%)");
                    sw.WriteLine($"  Available: {drive.AvailableFreeSpace / (1024.0 * 1024.0 * 1024.0):F2} GB");
                    sw.WriteLine();
                }
                catch (Exception ex)
                {
                    sw.WriteLine($"  Error processing drive {drive.Name}: {ex.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            sw.WriteLine($"Storage info error: {ex.Message}");
        }
    }
    private static void NetworkInfo(StreamWriter sw)
    {
        sw.WriteLine("=== NETWORK INFO ===");
        try
        {
            string hostName = Dns.GetHostName();
            sw.WriteLine($"Host Name: {hostName}");

            IPAddress[] addresses = Dns.GetHostAddresses(hostName);
            sw.WriteLine("IP Addresses:");
            foreach (IPAddress address in addresses)
            {
                sw.WriteLine($"  {address} ({address.AddressFamily})");
            }

            var ipProps = IPGlobalProperties.GetIPGlobalProperties();
            sw.WriteLine($"Active TCP Connections: {ipProps.GetActiveTcpConnections().Length}");
            sw.WriteLine($"Active UDP Listeners: {ipProps.GetActiveUdpListeners().Length}");
        }
        catch (Exception ex)
        {
            sw.WriteLine($"Network info error: {ex.Message}");
        }
    }
    private static void MonitorsInfo(StreamWriter sw)
    {
        sw.WriteLine("=== MONITOR INFO ===");
        using var searcher = new ManagementObjectSearcher(@"root\wmi", "SELECT * FROM WmiMonitorID");
        int monitorCount = 0;
        foreach (ManagementObject obj in searcher.Get().Cast<ManagementObject>())
        {
            monitorCount++;
            string name = GetString((ushort[])obj["UserFriendlyName"]);
            string serial = GetString((ushort[])obj["SerialNumberID"]);

            sw.WriteLine($"Monitor: {name.Trim()}");
            sw.WriteLine($"  Serial: {serial.Trim()}");
        }
        sw.WriteLine($"  Total Monitors: {monitorCount}");
    }
    private static void MonitorsInfoDetailed(StreamWriter sw)
    {
        sw.WriteLine("=== DISPLAY MONITORS ===");

        try
        {
            using var searcher = new ManagementObjectSearcher(@"root\wmi",
                "SELECT * FROM WmiMonitorID");

            using var searcherParams = new ManagementObjectSearcher(@"root\wmi",
                "SELECT * FROM WmiMonitorBasicDisplayParams");

            var monitors = searcher.Get().Cast<ManagementObject>().ToList();
            var monitorParams = searcherParams.Get().Cast<ManagementObject>().ToList();

            int monitorCount = 0;

            for (int i = 0; i < monitors.Count; i++)
            {
                monitorCount++;
                var monitor = monitors[i];

                string name = GetString((ushort[])monitor["UserFriendlyName"]);
                string serial = GetString((ushort[])monitor["SerialNumberID"]);
                string manufacturer = GetString((ushort[])monitor["ManufacturerName"]);
                string product = GetString((ushort[])monitor["ProductCodeID"]);

                
                ushort? week = monitor["WeekOfManufacture"] as ushort?;
                ushort? year = monitor["YearOfManufacture"] as ushort?;

                sw.WriteLine($"Monitor #{monitorCount}:");
                sw.WriteLine($"  Model: {name.Trim()}");
                sw.WriteLine($"  Manufacturer: {manufacturer.Trim()}");
                sw.WriteLine($"  Product Code: {product.Trim()}");
                sw.WriteLine($"  Serial: {serial.Trim()}");

                if (week.HasValue && year.HasValue)
                    sw.WriteLine($"  Manufactured: Week {week}, {year}");

                
                if (i < monitorParams.Count)
                {
                    var param = monitorParams[i];
                    sw.WriteLine($"  Max Resolution: {param["MaxHorizontalResolution"]}x{param["MaxVerticalResolution"]}");
                    sw.WriteLine($"  Video Input: {GetVideoInputType(Convert.ToUInt16(param["VideoInputType"]))}");
                }
            }

            sw.WriteLine($"Total Monitors: {monitorCount}");
        }
        catch (Exception ex)
        {
            sw.WriteLine($"Error getting monitor info: {ex.Message}");
            
            MonitorsInfo(sw);
        }
    }
    private static void SoftwareInfo(StreamWriter sw)
    {
        sw.WriteLine("=== SOFTWARE INFO ===");
        try
        {

            sw.WriteLine($"Running Processes: {Process.GetProcesses().Length}");

            sw.WriteLine("[.NET FRAMEWORK]");
            string frameworkPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "Microsoft.NET\\Framework");
            if (Directory.Exists(frameworkPath))
            {
                foreach (var dir in Directory.GetDirectories(frameworkPath))
                {
                    string dirName = Path.GetFileName(dir);
                    if (dirName.StartsWith("v") && !dirName.Contains("64") && !dirName.Contains("Client"))
                    {
                        sw.WriteLine($"  {dirName}");
                    }
                }
            }

            sw.WriteLine("[ENVIRONMENT VARIABLES]");
            sw.WriteLine($"  OS: {Environment.GetEnvironmentVariable("OS")}");
            sw.WriteLine($"  PROCESSOR_ARCHITECTURE: {Environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE")}");
            sw.WriteLine($"  NUMBER_OF_PROCESSORS: {Environment.GetEnvironmentVariable("NUMBER_OF_PROCESSORS")}");
            sw.WriteLine($"  TEMP: {Environment.GetEnvironmentVariable("TEMP")}");
            sw.WriteLine($"  PATH: {Environment.GetEnvironmentVariable("PATH")?[..Math.Min(100, Environment.GetEnvironmentVariable("PATH")?.Length ?? 0)]}...");
        }
        catch (Exception ex)
        {
            sw.WriteLine($"Software info error: {ex.Message}");
        }
    }
    private static void SecurityInfo(StreamWriter sw)
    {
        sw.WriteLine("=== SECURITY INFO ===");
        try
        {
            sw.WriteLine($"Running as Admin: {IsUserAdministrator()}");
            sw.WriteLine($"User Interactive: {Environment.UserInteractive}");
            sw.WriteLine($"System Page Size: {Environment.SystemPageSize} bytes");

            sw.WriteLine("[SECURITY SOFTWARE]");
            using var searcher = new ManagementObjectSearcher(@"root\SecurityCenter2", "SELECT * FROM AntivirusProduct");
            foreach (ManagementObject obj in searcher.Get().Cast<ManagementObject>())
            {
                sw.WriteLine($"  Product: {obj["displayName"]}");
                sw.WriteLine($"    State: {GetAntivirusState(Convert.ToInt32(obj["productState"]))}");

            }
        }
        catch (Exception ex)
        {
            sw.WriteLine($"Security info error: {ex.Message}");
        }
    }
    private static void PrintSensorsOnly(StreamWriter sw)
    {
        Computer computer = new()
        {
            IsCpuEnabled = true,
            IsGpuEnabled = true,
            IsMemoryEnabled = true,
            IsMotherboardEnabled = true,
            IsControllerEnabled = true,
            IsNetworkEnabled = true,
            IsStorageEnabled = true
        };

        computer.Open();
        computer.Accept(new UpdateVisitor());

        foreach (IHardware hardware in computer.Hardware)
        {
            sw.WriteLine($"\n[{hardware.Name}]");

            
            foreach (ISensor sensor in hardware.Sensors)
            {
                if (sensor.Value.HasValue)
                {
                    string unit = GetSensorUnit(sensor.SensorType);
                    sw.WriteLine($"  {sensor.Name,-25}: {sensor.Value.Value,8:F1} {unit}");
                }
            }

            
            foreach (IHardware sub in hardware.SubHardware)
            {
                sw.WriteLine($"  > {sub.Name}:");
                foreach (ISensor sensor in sub.Sensors)
                {
                    if (sensor.Value.HasValue)
                    {
                        string unit = GetSensorUnit(sensor.SensorType);
                        sw.WriteLine($"      {sensor.Name,-20}: {sensor.Value.Value,6:F1} {unit}");
                    }
                }
            }
        }

        computer.Close();
    }
    public static void CreateDetailedReport()
    {
        try
        {
            string desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            string folderPath = Path.Combine(desktopPath, "SystemReport");
            Directory.CreateDirectory(folderPath);

            string reportFile = Path.Combine(folderPath, $"report_{DateTime.Now:yyyy-MM-dd_HH-mm-ss}.txt");

            using (StreamWriter sw = new(reportFile))
            {
                
                Header(sw);
                sw.WriteLine(new string('=', 60));
                
                GeneralInfo(sw);
                sw.WriteLine(new string('-', 40));
                
                HardwareInfo(sw);

                MonitorsInfoDetailed(sw);
                sw.WriteLine(new string('-', 40));
                
                StorageInfo(sw);
                sw.WriteLine(new string('-', 40));
                
                NetworkInfo(sw);
                NetWorkAdapters(sw);
                sw.WriteLine(new string('-', 40));
                
                SoftwareInfo(sw);
                SecurityInfo(sw);

                sw.WriteLine(new string('=', 60));
                sw.WriteLine("=== LIVE SENSORS DATA (LibreHardwareMonitor) ===");
                sw.WriteLine(new string('=', 60));
                
                PrintSensorsOnly(sw);
            }

            AnsiConsole.MarkupLine($"[green]✓[/] Report created: {reportFile}");
            Process.Start("explorer.exe", folderPath);
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[red]✗[/] Error: {ex.Message}");
        }
    }
    private static bool IsUserAdministrator()
    {
        try
        {
            var identity = WindowsIdentity.GetCurrent();

            var principal = new WindowsPrincipal(identity);

            return principal.IsInRole(WindowsBuiltInRole.Administrator);

        }
        catch { return false; }
    }
    private static string GetArchitecture(int archCode)
    {
        return archCode switch
        {
            0 => "x86",
            1 => "MIPS",
            2 => "Alpha",
            3 => "PowerPC",
            5 => "ARM",
            6 => "IA64",
            9 => "x64",
            12 => "ARM64",
            _ => $"Unknown ({archCode})"
        };
    }
    private static string GetMemoryType(int typeCode)
    {
        return typeCode switch
        {
            0 => "Unknown",
            1 => "Other",
            2 => "DRAM",
            3 => "Synchronous DRAM",
            4 => "Cache DRAM",
            5 => "EDO",
            6 => "EDRAM",
            7 => "VRAM",
            8 => "SRAM",
            9 => "RAM",
            10 => "ROM",
            11 => "Flash",
            12 => "EEPROM",
            13 => "FEPROM",
            14 => "EPROM",
            15 => "CDRAM",
            16 => "3DRAM",
            17 => "SDRAM",
            18 => "SGRAM",
            19 => "RDRAM",
            20 => "DDR",
            21 => "DDR2",
            22 => "DDR2 FB-DIMM",
            24 => "DDR3",
            25 => "FBD2",
            26 => "DDR4",
            _ => $"Unknown ({typeCode})"
        };
    }
    private static string GetAntivirusState(int state)
    {
        bool enabled = ((state >> 16) & 0xFF) == 1;
        bool upToDate = ((state >> 8) & 0xFF) == 1;
        return $"Enabled: {enabled}, Up to date: {upToDate}";
    }
    private static string GetString(ushort[] identifiers)
    {
        if (identifiers == null) return "Unknown";
        string result = "";
        foreach (ushort i in identifiers)
        {
            if (i == 0) break;
            result += (char)i;
        }
        return result;
    }
    private static string GetSensorUnit(SensorType type)
    {
        return type switch
        {
            SensorType.Voltage => "V",
            SensorType.Clock => "MHz",
            SensorType.Temperature => "°C",
            SensorType.Load => "%",
            SensorType.Fan => "RPM",
            SensorType.Flow => "L/h",
            SensorType.Control => "%",
            SensorType.Level => "%",
            SensorType.Factor => "",
            SensorType.Power => "W",
            SensorType.Data => "GB",
            SensorType.SmallData => "MB",
            _ => ""
        };
    }
    private static string GetVideoInputType(ushort type)
    {
        return type switch
        {
            0 => "Unknown",
            1 => "VGA",
            2 => "DVI",
            3 => "HDMI",
            4 => "DisplayPort",
            5 => "Composite",
            6 => "S-Video",
            7 => "Component",
            _ => $"Type {type}"
        };
    }
}